spring:
  application:
    name: hortinis-sync
  main:
    log-startup-info: false

logging:
  structured:
    format:
      console: logstash

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
